// todolist-react/src/app.js
import React from 'react';
import Head from './views/head.js';
import Content from './views/content.js';
import Foot from './views/foot.js';


class App extends React.Component{
    constructor(props){
        super(props)
        this.state = {
            data: this.props.data
        }
    }
    addListParent(val){
        let d = this.state.data;
        d.push({
            id: Math.random(),
            title: val,
            isSelected: false
        })
        this.setState({
            data : d
        })
    }
    removeListParParent(i){
        
        let d = this.state.data;
        d.splice(i,1)
        this.setState({
            data : d
        })
    }
    checkedListParParent(i){
        let d = this.state.data;
        let isChecked = d[i].isSelected;
        
        d[i].isSelected = !isChecked
        this.setState({
            data: d
        })
    }
    editToDoTextProParent(id,text){
        let obj = this.state.data.filter((item)=>{
            return item.id === id
        })
        obj[0].title = text;
        this.setState({
            data: this.state.data
        })
    }
    render(){
        let content,footer;
        let arr = this.state.data;
        let num = arr.length;
        arr.forEach((item) => {
            if(item.isSelected){
                num--
            }
        })
        if(this.state.data.length){
            content = <Content 
                        data={this.state.data}
                        removeListParParent={this.removeListParParent.bind(this)}
                        checkedListParParent={this.checkedListParParent.bind(this)}
                        editToDoTextProParent={this.editToDoTextProParent.bind(this)}
                    ></Content>
            footer = <Foot num={num}></Foot>
        }
        return (
            
            <section className="todoapp">
                <div>
                    <Head 
                        data={this.state.data}
                        addListParent={this.addListParent.bind(this)}
                    ></Head>
                    {content}
                    {footer}
                </div>
            </section>
        )
    }
};
export default App;

// todolist-vue/src/App.vue
<template>
  <div id="app">
    <section class="todoapp">
      <custom-header @add-list="addListListener"></custom-header>
      <custom-content 
        :st="list"
        @remove="removeHandel"
        :checkAll="selectedAll"
        v-show="list.length"
        @all-select='allHandel'
      ></custom-content>
      <custom-footer :num="unselectedList" :st="list"></custom-footer> 
    </section>
  </div>
</template>

<script>
  import Header from './components/header'
  import Content from './components/content'
  import Footer from './components/footer'

  let data = [
    {
      title: '天气很好',
      selected: false
    },
    {
      title: '嗯嗯',
      selected: true
    }
  ]
  export default {
    name: 'app',
    data () {
      return{
        list: data
      }
    },
    components: {
      'custom-header': Header,
      'custom-content': Content,
      'custom-footer': Footer
    },
    methods:{
      addListListener(value){
        this.list.push({
          title:value,
          selected: false
        })
      },
      removeHandel(index){
        this.list.splice(index,1)
      },
      allHandel(val){
        this.list.forEach(item => {
          item.selected = val
        })
      }
    },
    computed:{
      selectedList(){
        return this.list.filter(item => item.selected)
      },
      unselectedList(){
        return this.list.length - this.selectedList.length
      },
      selectedAll(){
        return this.selectedList.length === this.list.length
      }
    }
  }
</script>
